apiVersion: v1
kind: ConfigMap
metadata:
  name: init-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS django;
    CREATE USER 'user'@'host' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON database.* TO 'user'@'host';
    FLUSH PRIVILEGES;
  init.django: |
    cd /home/python/app;
    python manage.py makemigrations && python manage.py migrate