kind: Deployment
apiVersion: apps/v1
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: kube-django-tutorial1:v1
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 512Mi
              cpu: "0.4"
          env:
          - name: DB_HOST
            value: django-mysql56
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
          - name: DB_USER
            value: django
          ports:
            - containerPort: 8000
              name: django
          volumeMounts:
            - name: init-django
              mountPath: /home/python/app/entrypoint.sh
      volumes:
      - name: init-django
        configMap:
          name: init-configmap
          items:
            - key: init.django
              path: init.django

---
kind: Service
apiVersion: v1
metadata:
  name: django-svc
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      name: django
  type: NodePort